config_version: 1.0
settings:
    # Choose your language, by default only English (en), French (fr) and German (de) are available. 
    # To create your own language file (for example in Spanish), create a file named "messages-es.yml" and put "es" below.
    language: en
    # Maximum CPS, beyond that, CPSs are not taken into account and an alert message is sent to the moderators (with permission verifplayer.moderator.receivealer) default: 17
    maxcps: 17
    # Time in seconds between each CPS alert sent to the moderator. The number of alerts displayed in the Mistletoe is not affected. Default (in seconds): 30 
    timebetweenalerts: 30
    # The size of a player's CPS history. The higher this value is, the more RAM it consumes. default: 10
    sizehistorycps: 10